default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 2012
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: logistic

test:
  <<: *default
  database: your_database_name_test

production:
  <<: *default
  database: your_database_name_production
